local nnoremap = require("johnvicke.keymap").nnoremap
local harpoon_mark = require("harpoon.mark")
local harpoon = require("harpoon")
local harpoon_io = require("harpoon.ui")

nnoremap("<leader>ho", function()
	harpoon_io.toggle_quick_menu()
end, { desc = "[H]arpoon [O]pen" })
nnoremap("<leader>ha", function()
	harpoon_mark.add_file()
end, { desc = "[H]arpoon [A]dd" })
nnoremap("<leader>a", function()
	harpoon_io.nav_file(1)
end, { desc = "Go to harpoon [A]" })
nnoremap("<leader>s", function()
	harpoon_io.nav_file(2)
end, { desc = "Go to harpoon [S]" })
nnoremap("<leader>d", function()
	harpoon_io.nav_file(3)
end, { desc = "Go to harpoon [D]" })
nnoremap("<leader>f", function()
	harpoon_io.nav_file(4)
end, { desc = "Go to harpoon [F]" })

harpoon.setup({})
