local m = require("johnvicke.util")

m.inoremap("kj", "<ESC>")
m.nnoremap("<leader>q", ":q<CR>")
m.nnoremap("<leader>x", ":qa<CR>")
m.nnoremap("<leader>w", ":w<CR>")
m.nnoremap("<leader>y", '"+y')
m.vnoremap("<leader>y", '"+y')
m.nnoremap("<C-u>", "<C-u>zz")
m.nnoremap("<C-d>", "<C-d>zz")
