#!/usr/bin/env bash

git clone https://github.com/alacritty/alacritty.git alacritty-git
cd alacritty-git
rustup override set stable
rustup update stable

sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

cargo build --release --no-default-features --features=$XDG_SESSION_TYPE

sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop

sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

mkdir -p $HOME/.zsh_functions/
cp extra/completions/_alacritty ${HOME}/.zsh_functions/_alacritty

sudo update-desktop-database

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50

cd ..

rm -rf alacritty-git
