#!/usr/bin/env zsh

sudo apt update --fix-missing

# Exa
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
sudo apt-get install ./exa_0.9.0-4_amd64.deb

sudo apt upgrade -y
