#!/usr/bin/env bash

echo "Installing ZSH with OH-MY-ZSH..."
sudo apt install zsh -y

#echo "Installing oh-my-zsh"
#sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

PLUGIN_PATH=$HOME/.oh-my-zsh/custom/plugins

# Vim mode
git clone https://github.com/jeffreytse/zsh-vi-mode $PLUGIN_PATH/zsh-vi-mode
# Z jump
git clone https://github.com/agkozak/zsh-z $PLUGIN_PATH/zsh-z
# Autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions $PLUGIN_PATH/zsh-autosuggestions
# Syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $PLUGIN_PATH/zsh-syntax-highlighting
# npm zsh-npm-scripts-autocomplete
git clone git@github.com:grigorii-zander/zsh-npm-scripts-autocomplete.git $PLUGIN_PATH/zsh-npm-scripts-autocomplete

echo "Changing shell to zsh"
sudo chsh -s "$(which zsh)"
