#!/usr/bin/env bash

function branch_exists() {
	local repo_dir=$1
	local branch_name=$2
	git -C "$repo_dir" show-ref --verify --quiet refs/heads/"$branch_name"
	return $?
}

function is_git_repo() {
	local dir=$1
	if [ -d "$dir/.git" ]; then
		return 0
	else
		return 1
	fi
}

for project in "$HOME/dev/anyfin/"*; do
	if ! is_git_repo "$project"; then
		echo "Skipping $project"
		continue
	fi

	current_branch=$(git -C "$project" rev-parse --abbrev-ref HEAD)

	if [ $current_branch == "main" ] || [ $current_branch == "master" ]; then
		git -C "$project" pull
	else
		git -C "$project" fetch -ap
	fi

done
