#!/usr/bin/env bash

addToPathFront /usr/local/go/bin
addToPathFront $HOME/.local/share/fnm
addToPathFront $HOME/.local/bin

addToPath /opt/nvim-linux-x86_64/bin
addToPath $BUN_INSTALL/bin
addToPath $HOME/.local/scripts
addToPath $HOME/go/bin
addToPath $HOME/.yarn/bin
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup
addToPath $HOME/Android/Sdk
addToPath $ANDROID_HOME/emulator
addToPath $ANDROID_HOME/tools
addToPath $ANDROID_HOME/tools/bin
addToPath $ANDROID_HOME/platform-tools
addToPath $HOME/Downloads/zig
addToPath $HOME/.rover/bin
addToPath $HOME/.pulumi/bin
addToPath $HOME/.local/share/pnpm
addToPath $HOME/.opencode/bin
