#!/usr/bin/env bash

addToPath /opt/nvim-linux64/bin
addToPathFront $BUN_INSTALL/bin
addToPathFront $HOME/.local/share/fnm
addToPathFront $HOME/.local/bin

addToPath /usr/local/go/bin
addToPath $HOME/.local/scripts
addToPath $HOME/go/bin
addToPath $HOME/.yarn/bin
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup
addToPath $HOME/Android/Sdk
addToPath $ANDROID_HOME/emulator
addToPath $ANDROID_HOME/tools
addToPath $ANDROID_HOME/tools/bin
addToPath $ANDROID_HOME/platform-tools
